
server:
  port: 9000
  tomcat:
    max-http-form-post-size: 100MB

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/template?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin123

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  application:
    name: template



#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl